In [ ]:
import numpy as np

In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr, type(arr))

arr2 = np.array([1, 2, 3, 4, "Amaan", 3.14])
print(arr2, type(arr2))

arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3, arr3.shape)

In [ ]:
arr1 = np.zeros((2, 3), dtype="int64")
print(arr1, arr1.shape)

arr22 = np.zeros((3, 3), dtype="int64")
print(arr22, arr22.shape)

arr4 = np.full((2, 3), 12, dtype="int64")
print(arr4, arr4.shape)

arr4 = np.eye(3)
print(arr4)

arr5 = np.arange(1, 11, 2)
print(arr5)

arr6 = np.linspace(1, 100, 3)
print(arr6)

In [ ]:
# properties
arrProp = np.array([[1, 2, 3], [5, 6, 7]])

# print(arrProp.shape)
print(arrProp.ndim)

float_arr = arrProp.astype(float)
print(float_arr)
print(float_arr.dtype)

In [ ]:
# Operations
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)
print("----------------------------")

arr2 = arr.reshape(2, 3)
print(arr2)

In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
print("-------------------")
flatted_array = arr.flatten()
print(flatted_array)

In [ ]:
# fancy and boolean indexing
arr = np.array([1, 2, 3, 4, 5])

# fancy indexing
idx = [0, 1, 2]
# print(arr[idx])

# boolean indexing -> Based on condition array in filtered out
print(arr[arr > 2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

In [ ]:
# slicing operation
arr = np.array([1, 2, 3, 4, 5])

sliced_array = arr[1: 4]

print(sliced_array)

In [22]:
# copy vs view

# 1.python list
# nums = [1, 2, 3, 4, 5]
# sub_list = nums[1:3]
# print(sub_list)
# sub_list[0] = 200
# print(sub_list)
# print(nums)

# 2.In numpy array
arr = np.array([1, 2, 3, 4, 5])
sub_arr = arr[1:4].copy()
print(sub_arr)
sub_arr[0] = 200
print(sub_arr)
print(arr)


[2 3 4]
[200   3   4]
[1 2 3 4 5]
