In [13]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])
print(arr, type(arr))

arr2 = np.array([1,2,3,4,"Amaan", 3.14])
print(arr2, type(arr2))

arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3, arr3.shape)

In [ ]:
arr1 = np.zeros((2,3), dtype = "int64")
print(arr1, arr1.shape)

arr22 = np.zeros((3,3), dtype = "int64")
print(arr22, arr22.shape)

arr4 = np.full((2,3),12, dtype = "int64")
print(arr4, arr4.shape)

arr4 = np.eye(3)
print(arr4)

arr5 = np.arange(1,11,2)
print(arr5)

arr6 = np.linspace(1, 100, 3)
print(arr6)

In [18]:
# properties
arrProp = np.array([[1,2,3],[5,6,7]])

# print(arrProp.shape)
print(arrProp.ndim)

float_arr = arrProp.astype(float)
print(float_arr)
print(float_arr.dtype)

2
[[1. 2. 3.]
 [5. 6. 7.]]
float64


In [21]:
# Operations
arr = np.array([1,2,3,4,5,6])
print(arr)
print("----------------------------")

arr2 = arr.reshape(2,3)
print(arr2)

[1 2 3 4 5 6]
----------------------------
[[1 2 3]
 [4 5 6]]
